### ISSUE TITLE
Can try tests this imap client

### ISSUE THREAD

**Issue by sergey144010** [sergey144010/php-imap-client#2]
@abdullahseba you can try this imap client. Here fixed inline attachments and other bugs. But the interface has been reworked, for example
```php
$email = $imapClient->getMessage(8);
echo $email->getHeaders()->subject.PHP_EOL;
echo $email->getBody()->plain.PHP_EOL;
```
see more https://github.com/sergey144010/php-imap-client/blob/master/docs/guide-en/Examples.md

**Comment by abdullahseba** [comment]
Ok will do :) In the process of upgrading my code to a newer framework.

**Comment by abdullahseba** [comment]
Sorry might take me some time to get round to it.
Its almost there but I need to get a few errors fixed that where caused by the new framework.

**Comment by sergey144010** [comment]
@TrueShutDown Try here your question about "Headers CC, BCC are correctly, but TO header include only one recipients"
